### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by Honga1** [tmf-code/hair#8]
- [x]  Fix falling hair sizes in portrait mode
- [x] Use recorded path for players
- [x] Replace the .png texture generation in friend-player with a prop from friend-players
- [x] Delete non existent players from frontend dict
- [x] Increase razor size on portrait
- [x] Use different styling for friend players
- [x] Don't re-render unchanged hairs - Did some perf improvements that should fix this.

- [x] Record 5 razors and see what it looks like.  - A bit hectic, but manageable. Maybe need to be smaller.
- [x] Implement ghost razors

Maybes
- [x] Add "Current Shavers" count - Not done - don't want
- [x] Try with lots of razors - Really hectic, needs instanced mesh

**Comment by Honga1** [comment]
Fix razor layering

**Comment by Honga1** [comment]
Experiment with starting rotations

**Comment by Honga1** [comment]
Change razor sizes

**Comment by Honga1** [comment]
Fix falling hair on mobile

**Comment by Honga1** [comment]
Add rooms

**Comment by Honga1** [comment]
- [ ] Add ghosts

**Comment by Honga1** [comment]
Send hair rotations
